---
- name: Install kibana configuration for Apache
  template:
    src: kibana.conf.j2
    dest: '{{ kibana_httpd_conf }}'
  notify: restart httpd

- name: Create kibana htpasswd file
  tags:
    - skip_ansible_lint # ignore ANSIBLE0012
  command: >
    htpasswd -cb {{ kibana_proxy_htpasswd }} {{ kibana_proxy_user }}
    {{ kibana_proxy_pass }}
  notify: restart httpd
