---
- name: Install httpd
  package:
    name: '{{ httpd_package_name }}'
    state: present
  when: manage_packages|default(false)

- name: Installing httpd modules
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ httpd_modules }}'
  when: manage_packages|default(false)

- name: ensure httpd configuration directory exists
  file:
    path: '{{ httpd_config_dir }}'
    state: directory

- name: ensure httpd configuration parts directory exists
  file:
    path: '{{ httpd_config_parts_dir }}'
    state: directory

- name: enable httpd service
  service:
    name: '{{ httpd_service_name }}'
    state: started
    enabled: yes
